theme: jekyll-theme-slate

title: uri-template
description: Javascript RFC 6570 URI template

show_downloads: true
google_analytics: G-6L3V8LTD4K

#highlighter: rouge
# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'
