theme: jekyll-theme-slate

title: uri-template
description: Javascript RFC 6570 URI template

show_downloads: true
google_analytics: G-6L3V8LTD4K

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: javascript